name: Go

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: staticcheck
      uses: reviewdog/action-staticcheck@v1.0.0
      with:
        reporter: github-check
        staticcheck_flags: -checks=inherit,-compile

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
